import { Question } from '../question';

export const AFL: Question[] = [
  {
    question: 'How many teams are in the AFL?',
    response_1: '16',
    response_2: '18',
    response_3: '17',
    response_4: '20',
    answer: 2,
  },
  {
    question: 'When did the AFL establish?',
    response_1: '1857',
    response_2: '1876',
    response_3: '1899',
    response_4: '1908',
    answer: 1,
  },
  {
    question: 'Which AFL team is the latest?',
    response_1: 'Lions',
    response_2: 'Fremantle',
    response_3: 'Giants',
    response_4: 'St Kilda',
    answer: 3,
  },
  {
    question: "The first AFL Player on 'I'm a celbrity get me out of here'?",
    response_1: 'Rory Sloane',
    response_2: 'Scott Pendkebury',
    response_3: 'Barry Hall',
    response_4: 'Dane Swan',
    answer: 3,
  },
  {
    question: 'How many teams have not won a premiership?',
    response_1: '6',
    response_2: '4',
    response_3: '2',
    response_4: '3',
    answer: 4,
  },
  {
    question: 'Who won the 2020 premiership?',
    response_1: 'Richmond',
    response_2: 'Swans',
    response_3: 'Geelong',
    response_4: 'Hawthorn',
    answer: 1,
  },
  {
    question: 'How many times has Collingwood lost a grand final?',
    response_1: '20',
    response_2: '28',
    response_3: '26',
    response_4: '10',
    answer: 3,
  },
  {
    question: 'What is Fremantles nickname?',
    response_1: 'Western Destroyers',
    response_2: 'Mantlers',
    response_3: 'Freo',
    response_4: 'F',
    answer: 3,
  },
  {
    question: 'Where are the West Coast Eagles from?',
    response_1: 'Adelaide',
    response_2: 'Sydney',
    response_3: 'Fremantle',
    response_4: 'Perth',
    answer: 4,
  },
  {
    question: 'Who is the CEO of the AFL?',
    response_1: 'Andrew Demetriou',
    response_2: 'Gillon McLachlan',
    response_3: 'Eddie McQuire',
    response_4: 'James Sutherland',
    answer: 2,
  },
];
