import { Question } from '../question';

export const CRICKET: Question[] = [
  {
    question: 'How many teams are in the BBL?',
    response_1: '10',
    response_2: '9',
    response_3: '7',
    response_4: '8',
    answer: 4,
  },
  {
    question: 'What does BBL stand for?',
    response_1: 'Big Ball League',
    response_2: 'Big Bash League',
    response_3: 'Brown Ball league',
    response_4: 'Big boy League',
    answer: 2,
  },
  {
    question: 'Which two countries compete in the Ashes series?',
    response_1: 'India v Australia',
    response_2: 'Austrlia v Africe',
    response_3: 'New Zealand v Australia',
    response_4: 'England v Australia',
    answer: 4,
  },
  {
    question: "Which Cricketer was the first one on 'I'm a celebrity get me out of here'?",
    response_1: 'Shane Warne',
    response_2: 'Merv Hughes',
    response_3: 'Michael Clarke',
    response_4: 'Freddie Flintoff',
    answer: 1,
  },
  {
    question: 'Which one of these is not a fielding position?',
    response_1: 'Silly mid on',
    response_2: 'Fine leg',
    response_3: 'Over the head',
    response_4: 'Second slip',
    answer: 3,
  },
  {
    question: 'Who was the champion in the 2015 World Cup',
    response_1: 'India',
    response_2: 'Australia',
    response_3: 'New Zealand',
    response_4: 'America',
    answer: 0,
  },
  {
    question: 'Who was the former CEO of Cricket Australia before Kevin Roberts?',
    response_1: 'Gillon McLachlan',
    response_2: 'David Peever',
    response_3: 'Earl Eddings',
    response_4: 'James Sutherlan',
    answer: 4,
  },
  {
    question: 'Who won the 2017 BBL Grand Final',
    response_1: 'Strikers',
    response_2: 'Hurricanes',
    response_3: 'Scorchers',
    response_4: 'Sizers',
    answer: 3,
  },
  {
    question: 'What surface is Cricket traditionally played on?',
    response_1: 'Dirt',
    response_2: 'Hardened sand',
    response_3: 'Astroturf',
    response_4: 'Grass',
    answer: 4,
  },
  {
    question: 'When was BBL established',
    response_1: '2011',
    response_2: '2001',
    response_3: '1999',
    response_4: '2013',
    answer: 1,
  },
];
